language: node_js
node_js: "8.11.1"
script: npm run lint && npm run test && npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
  on:
    branch: master
